spring:
  main:  #关闭 banner 注意 off要带引号
    banner-mode: "off"
  profiles:
    active: dev
server:
  servlet:
    context-path: /framework
# 关闭mybatis-plus banner输出
mybatis-plus:
  global-config:
    banner: false

# dubbo  配置信息
dubbo:
  scan:
    base-packages: com.xin.dubbo.consumer
  registry:
    address: zookeeper://127.0.30.185:2181
  consumer:
    application: my-dubbo-consumer
    check: false


